spring:
  application:
    name: tripsync-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tripsync_db}
    username: ${DB_USERNAME:tripsync_user}
    password: ${DB_PASSWORD:tripsync_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.tripsync: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN

# AWS Configuration
aws:
  region: ${AWS_REGION:us-east-1}
  sqs:
    queue-url: ${AWS_SQS_QUEUE_URL:}
  ses:
    from-email: ${AWS_SES_FROM_EMAIL:noreply@tripsync.com}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
  allowed-headers: "*"
  allow-credentials: true